backend:
  path:
    /Users/olaputin/work/rs/Python-Backends/revelV2
  bin:
    /Users/olaputin/virtenv/rs/bin/python
pootle:
  enable:
    True
  bin:
    /Users/olaputin/dev/pootle/env/bin/pootle

translations:
  path:
    /Users/olaputin/dev/pootle/env/lib/python2.7/site-packages/pootle/translations

msgmerge:
  /usr/local/bin/msgmerge
release:
  available:
    master:
      master
    r2.16:
      release/2.16
    r2.17:
      release/2.17
    r2.18:
      release/2.18
  enable:
    - master
    - r2.16
    - r2.17
    - r2.18


languages:
  - pl
  - ru
  - de
  - es
  - et
  - fr
  - it
  - lt
  - th

commit:
  True

makemessages:
  backend:
    True
  pos:
    True

redis:
  host:
    localhost
  port:
    6379

debug:
  True