backend:
  path:
    __FIX_IT__
  bin:
    __FIX_IT_

pootle:
  enable:
    True
  bin:
    __FIX_IT__

translations:
  path:
    __APPLICATION_PATH__/translations
  backup:
    enable:
      True
    path:
      __APPLICATION_PATH__/backup

msgmerge: /usr/local/bin/msgmerge

release:
  available:
    master:
      branch: master
      index: 1.0
    r2.16:
      branch: release/2.16
    r2.17:
      branch: release/2.17
    r2.18:
      branch: release/2.18
    r2.19:
      branch: release/2.19
    r2.20:
      branch: release/2.20
    r2.21:
      branch: release/2.21
    r2.22:
      branch: release/2.22
    r2.23:
      branch: release/2.23

  enable:
    - master
    - r2.16
    - r2.17
    - r2.18
    - r2.19
    - r2.20
    - r2.21
    - r2.22
    - r2.23
  default_index: 0.5

git:
  enable:
    True
  commit:
    True
  pull:
    True


compilemessages: True

languages:
  - pl
  - ru
  - de
  - es
  - et
  - fr
  - it
  - lt
  - th


makemessages:
  backend:
    True
  pos:
    True

redis:
  host:
    localhost
  port:
    6379
debug:
  True

split:
  settings:
    path:
      - core/settings.py
      - dashboard/tips.py
    languages:
      - ru
      - pl
      - et
      - lt
    release:
      - master
    parts:
      - django
      - djangojs

logging:
  version: 1
  logging_dir: '__LOG_PATH__'
  formatters:
    default:
      format: '%(asctime)s %(levelname)s %(message)s'
    default:
      format: '%(asctime)s %(levelname)s %(name)s %(message)s'
    simple:
      format: '%(levelname)s %(message)s'

  handlers:
    checkout_file:
      level: DEBUG
      formatter: default
      class: 'logging.FileHandler'
      filename: '__LOG_PATH__/checkout.log'

    commit_file:
      level: DEBUG
      formatter: default
      class: 'logging.FileHandler'
      filename: '__LOG_PATH__/commit.log'

    save_file:
      level: DEBUG
      formatter: default
      class: 'logging.FileHandler'
      filename: '__LOG_PATH__/save.log'

    console:
      level: DEBUG
      class: 'logging.StreamHandler'
      formatter: simple

  loggers:
    checkout:
      handlers:
        - checkout_file
        - console
      level: DEBUG

    splitcheckout:
      handlers:
        - checkout_file
        - console
      level: DEBUG

    commit:
      handlers:
        - commit_file
        - console
      level: DEBUG

    save:
      handlers:
        - save_file
        - console
      level: DEBUG

    splitsave:
      handlers:
        - save_file
        - console
      level: DEBUG

    createreport:
      handlers:
        - console
      level: DEBUG

    weekrepreport:
      handlers:
        - console
      level: DEBUG

    releasestatreport:
      handlers:
        - console
      level: DEBUG

rqworker:
  timeout: 3600
  result_ttl: 86400